### ISSUE TITLE
Apply for rawdata

### ISSUE THREAD

**Issue by mengchengyao** [nealpsmith/peanut_pscdr3#1]
Hi,
Thank you for your great work in Identifing of antigen-specific  TCR sequences, could you provide rawdata for test, just like 107_BL_Arah1_CD154-.tsv and 107_BL_Arah1_CD154+.tsv file.

Many thanks

**Comment by nealpsmith** [comment]
Hi @semir2 could you please reach out to me over email for this?  You can reach me at nsmith19@mgh.harvard.edu.  We can provide data, but just want to know the research group you are a part of and the analyses you will be doing with the data. Thanks!

**Comment by mengchengyao** [comment]
> Hi @semir2 could you please reach out to me over email for this? You can reach me at [nsmith19@mgh.harvard.edu](mailto:nsmith19@mgh.harvard.edu). We can provide data, but just want to know the research group you are a part of and the analyses you will be doing with the data. Thanks!

Many thanks
